# Generated by Django 4.2.5 on 2024-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
